### ISSUE TITLE
Please add a LICENSE

### ISSUE THREAD

**Issue by manodeep** [mozonaut/vp2intersect#1]
@mozonaut Thanks for your work and for releasing the code. Could you please add a permissive license so others can read/reuse it?

Thanks in advance!
Manodeep

**Comment by mozonaut** [comment]
Feel free to use it as you wish. The restrictive license is just there so Intel can license it if they want to offer a software version of their VP2INTERSECT instructions. That said I recommend you check the function 

> **'inline uint16_t _mm512_2intersect_epi32_mask(__m512i a, int32_t * const b)'**

which is pretty trivial and usually the fastest.

**Comment by manodeep** [comment]
That's great - thanks!
